title: "鉄道敷設バトルゲーム開発葛藤録"
summary: "\
  鉄道バトルシミュレーションゲームを個人開発した際に直面した設計と実装のジレンマの回顧録です。\
  いかにして仕様を決めたのか、なぜ機能の実装を断念したのか、意外なところで役立ったアルゴリズム、など\
  開発中に起きた悩みと発見を書き記していきます。"
topics:
  - ゲーム開発
  - 設計
  - アルゴリズム
  - UX
  - 鉄道
published: false
price: 0
chapters:
  - prologue
  - introduction
  - diagram
